#! /usr/bin/env python
import sys
import argparse

parser = argparse.ArgumentParser(description="D-matrix to Energy converter")

parser.add_argument("-v", "--verbose", help="Make the output verbose", action="store_true")
parser.add_argument("-f","--file", help="Input file where the matrix is.", action="store")
parser.add_argument("--format", help="Format in which the matrix is saved (default vasp)", action="store", default="vasp")

args = parser.parse_args()

if args.verbose:
    print("Making the output verbose...")
    VERBOSE=True
else:
    VERBOSE=False


MATRIX_FILE = args.file

def parse_vasp(filePath):
    """Parses the D-Matrix information from filePath in VASP format

    :filePath: TODO
    :returns: TODO

    """
    pass

if __name__=="__main__":
    pass
